### PR TITLE
Release 1.0

### PR DESCRIPTION
**Pull request by phatblat**
Bumped the version to 1.0.0 in both RBQSafeRealmObject & SafeRealmObject since it looks like they are always released together, however nothing changed in RBQSafeRealmObject.

### CODE REVIEW

**Comment by phatblat** [comment]
@bigfish24 if you add me as an owner (octop.ad email) on these two pods, I can push the updated specs to CocoaPods trunk.

**Comment by bigfish24** [comment]
Will do! Give me an hour or so.

**Comment by bigfish24** [comment]
@phatblat added! (also added you to RBQFetchedResultsController/SwiftFetchedResultsController, ABFRealmMapView/RealmMapView)

**Comment by phatblat** [comment]
1.0 is live now!

screen shot 2016-11-12 at 8 11 16 am
screen shot 2016-11-12 at 8 16 55 am

**Comment by bigfish24** [comment]
🎉🎉🎉

**Pull request merged**
